const ShopActionTypes = {
        COLLECTIONS_FETCH_START: 'COLLECTIONS_FETCH_START',
        COLLECTIONS_FETCH_SUCCESS: 'COLLECTIONS_FETCH_SUCCESS',
        COLLECTIONS_FETCH_FAILURE: 'COLLECTIONS_FETCH_FAILURE',
}
export default ShopActionTypes;
